[package]
name = "sphinxcrypto"
version = "0.0.2"
authors = ["David Stainton <dstainton415@gmail.com>"]
description = "Sphinx mixnet packet cryptography"
homepage = "https://github.com/applied-mixnetworks/rust-sphinxcrypto"
repository = "https://github.com/applied-mixnetworks/rust-sphinxcrypto"
documentation = "https://docs.rs/sphinxcrypto/"
readme = "README.rst"
keywords = ["cryptography", "sphinx", "mixnet", "crypto", "mix"]
license = "MIT"

[dependencies]
arrayref = "^0.3.4"
subtle = "0.6.0"
byteorder = "1.2.2"
rustc-serialize = "0.3"
rand = "^0.4.2"
rust-lioness = "^0.1.3"
ecdh_wrapper = "0.0.0"
rust-crypto = "^0.2"
tiny-keccak = "1.3"

[dev-dependencies]
rand = "^0.4.2"
rustc-serialize = "0.3"
